title: "Escalenidades*"
description: "~ música com expressão de género ~"
email:
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 8
disqus: ''
locale: pt_PT
lang: pt_pt
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Social
social:
  instagram: https://www.instagram.com/escalenidades/
  facebook: https://www.facebook.com/escalenidades
  twitter: https://twitter.com/escalenidades

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
